project:
  name: "my-project"
  description: "This is my project"
  destinations:
    - namespace: "default"
      server: "https://kubernetes.default.svc"

application:
  name: "my-application"
  destination:
    namespace: "default"
    server: "https://kubernetes.default.svc"
  source:
    path: "apps"
    repourl: "https://github.com/ctablero/argocd.git"
    targetrevision: "HEAD"
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
